[[plugins]]
repo = 'Shougo/dpp.vim'
rtp = ''

[[plugins]]
repo = 'Shougo/dpp-ext-lazy'
rtp = ''

[[plugins]]
repo = 'Shougo/dpp-ext-toml'
hook_add = '''
" enable dpp toml syntax.
if !has('nvim')
  autocmd UserCmd CursorHold ~/.config/nvim/*.toml call dpp#ext#toml#syntax()
endif
'''

[[plugins]]
repo = 'Shougo/dpp-ext-local'

[[plugins]]
repo = 'Shougo/dpp-ext-installer'

[[plugins]]
repo = 'Shougo/dpp-ext-packspec'

[[plugins]]
repo = 'Shougo/dpp-protocol-git'

